"$schema" = "https://starship.rs/config-schema.json"

format = """
[](c_blue_light)\
$os\
$username\
[](fg:c_blue_light bg:c_blue_main)\
$directory\
[](fg:c_blue_main bg:c_indigo_soft)\
$git_branch\
$git_status\
[](fg:c_indigo_soft bg:c_blue_soft)\
$rust\
$golang\
$nodejs\
$java\
$python\
[](fg:c_blue_soft bg:c_slate_light)\
$docker_context\
[](fg:c_slate_light bg:c_sky)\
$time\
[ ](fg:c_sky)\
$line_break$character"""

palette = "blue_light"

[palettes.blue_light]
c_blue_light = "#bfdbfe"
c_blue_main = "#93c5fd"
c_blue_soft = "#60a5fa"
c_blue_deep = "#3b82f6"
c_indigo_soft = "#818cf8"
c_sky = "#e0f2fe"
c_cyan = "#67e8f9"
c_slate_light = "#e2e8f0"
c_dark = "#1e293b"
c_text = "#0f172a"
c_error = "#ef4444"

[os]
disabled = false
format = "[$symbol]($style)"

[os.symbols]
Ubuntu = "[](fg:c_dark bg:c_blue_light)"
Fedora = "[](fg:c_dark bg:c_blue_light)"
NixOS = "[](fg:c_dark bg:c_blue_light)"
Arch = "[](fg:c_dark bg:c_blue_light)"

[username]
show_always = true
style_user = "bg:c_blue_light fg:c_dark"
style_root = "bg:c_blue_light fg:c_dark"
format = "[ $user ]($style)"

[directory]
style = "fg:c_text bg:c_blue_main"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = "󰝚 "
Pictures = " "

[git_branch]
symbol = ""
style = "bg:c_indigo_soft"
truncation_length = 12
truncation_symbol = "…"
format = "[[ $symbol $branch(:$remote_branch) ](fg:white bg:c_indigo_soft)]($style)"

[git_status]
style = "bg:c_indigo_soft"
format = "[[($all_status$ahead_behind )](fg:c_dark bg:c_indigo_soft)]($style)"

[nodejs]
symbol = ""
style = "bg:c_blue_soft"
format = "[[ $symbol( $version) ](fg:white bg:c_blue_soft)]($style)"

[rust]
symbol = ""
style = "bg:c_blue_soft"
format = "[[ $symbol( $version) ](fg:white bg:c_blue_soft)]($style)"

[golang]
symbol = ""
style = "bg:c_blue_soft"
format = "[[ $symbol( $version) ](fg:white bg:c_blue_soft)]($style)"

[java]
symbol = " "
style = "bg:c_blue_soft"
format = "[[ $symbol( $version) ](fg:white bg:c_blue_soft)]($style)"

[python]
symbol = ""
style = "bg:c_blue_soft"
format = "[[ $symbol( $version) ](fg:white bg:c_blue_soft)]($style)"

[docker_context]
symbol = ""
style = "bg:c_slate_light"
format = "[[ $symbol( $context) ](fg:c_dark bg:c_slate_light)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:c_sky"
format = "[[  $time ](fg:c_dark bg:c_sky)]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:c_blue_deep)"
error_symbol = "[](bold fg:c_error)"
vimcmd_symbol = "[](bold fg:c_blue_deep)"
vimcmd_replace_one_symbol = "[](bold fg:c_blue_soft)"
vimcmd_replace_symbol = "[](bold fg:c_error)"
vimcmd_visual_symbol = "[](bold fg:c_indigo_soft)"
